
services:
  webserver:
    networks:
      - smartcity

  scheduler:
    networks:
      - smartcity

  triggerer:
    networks:
      - smartcity

networks:
  smartcity:
    driver: bridge
    external: true